### ISSUE TITLE
Support CI

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb-client-py#3]
Thie project needs CI based on Github Actions to ensure the quality of development. And now about the CI what I can come up with is these jobs:
- python style check
- rust style check: (refer to [actions in ceresdb](https://github.com/CeresDB/ceresdb/blob/main/.github/workflows/ci.yml))
   - rustfmt
   - clippy

And as for unit tests, now no unit test in this project has been provided and the test framework of the python project has not been decided yet so I suggest skipping the UT part in the CI for now.

**Comment by messense** [comment]
Adding style checks are easy. I was thinking more about adding CI to build Python wheels, I can do this along the way.

I do think the [dependency issue](https://github.com/CeresDB/ceresdb-client-py/pull/2#issuecomment-1186925905) I mentioned should be addressed first, otherwise CI could be terribly slow.

**Comment by waynexia** [comment]
That all-in-one dependent delegate brings lots of unnecessary deps to other crates like this client. I've suffered from it already 😷
